title: Thomas Reinert
baseURL: "https://thomas-reinert.github.io/website/"
theme: PaperModX

enableRobotsTXT: true
enableEmoji: true

params:
  description: "der blinde Keynote Speaker"
  author: Reorx
  images:
    - cover.png
  favicon: favicon.ico
  #logo:
  #  icon: images/logo.svg
  DateFormat: "2006-01-02"
  useCustomAnalytics: true
  mainSections:
    - posts
    - notes

  # theme params
  DisableLanguageSwitch: true
  TocOpen: true
  TocSide: right
  EnableInstantClick: false
  EnableImageZoom: true
  ShowShareButtons: true
  ShareButtons:
    - twitter
    - telegram
  ShowReadingTime: true
  ShowWordCount: true
  ShowCodeCopyButtons: true
  ShowPostNavLinks: true
  Email: hello@example.com

  socialIcons:
    - name: github-simple
      url: "https://github.com/reorx"
    - name: twitter-simple
      url: "https://twitter.com/novoreorx"
    - name: telegram-simple
      url: "https://t.me/reorx_share"
    - name: rss-simple
      url: "feed.xml"
    - name: gmail
      url: email

  socialAccounts:
    twitter:
      username: novoreorx

  homeInfoParams:
    Title: "der blinde Keynote Speaker"
    Content: |
      Thomas Reinert ist ein Meister darin, Dunkelheit in Licht zu verwandeln. Als visionärer Speaker und Inspirator mit einer außergewöhnlichen Lebensgeschichte verbindet er auf einzigartige Weise die Tiefen menschlicher Erfahrungen mit dem Streben nach persönlichem und professionellem Wachstum.
      Seine Mission: mit so vielen Menschen wie möglich von Herz zu Herz zu sprechen, sie zu inspirieren und dann zu beobachten, was sich daraus entfaltet. 
      Auf dieser Website teilt Thomas seine Erkenntnisse, Geschichten und die Essenz seines zwölf Schritte umfassenden Prozesses, der Hindernisse in Stufen zum Erfolg verwandelt. 
      Entdecken Sie, wie Sie Resilienz aufbauen, Herausforderungen meistern und Ihr eigenes Licht heller leuchten lassen können.

  #commentSystems:
  #  disqus:
  #    shortname: reorx
  #  remark42:
  #    url: https://remark42.reorx.com
  #    site: reorx.github.io
  #  telegramWidget:
  #    channel: reorx_share
  #    accentColor: "9077e1"
  #    limit: 20
  #defaultCommentSystems:
  #  remark42: true

permalinks:
  notes: /:section/:year/:month/:slugorfilename

# prefer feed.xml rather than index.xml
outputFormats:
  RSS:
    mediatype: "application/rss"
    baseName: "feed"

menu:
  main:
    - name: Posts
      url: /posts/
      weight: 1
    - name: Notes
      url: /notes/
      weight: 2
    - name: Newsletter
      url: /newsletter/
      weight: 3
    - name: Archives
      url: /archives/
      weight: 4

languages:
  en:
    languageName: "English"

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: dracula
    lineNos: false
    noClasses: false
